# Generated by Django 5.0.7 on 2024-08-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='limodel',
            new_name='lmodel',
        ),
    ]
